Repository edenlabllc/ehealth.api, pull requests merged in 2018-12, with the labels that each got.

#3749 EHealth-3654: suspend contracts on employee deactivation
  apps/core/lib/core/employees/employee_creator.ex
  apps/core/test/support/expectations/mithril.ex
  apps/ehealth/test/web/controllers/contract_request/capitation_controller_test.exs
  apps/ehealth/test/web/controllers/contract_request/reimbursement_controller_test.exs
  apps/ehealth/test/web/controllers/employee_request_controller_test.exs
  apps/ehealth/test/web/controllers/legal_entity_controller_test.exs
Labels: status/in-progress

#3742 fix year condition + remove deduplication
  apps/core/lib/core/contract_requests/validator.ex
  apps/ehealth/lib/ehealth.ex
  apps/ehealth/lib/ehealth/duplicate_persons/cleanup.ex
  apps/ehealth/lib/ehealth/duplicate_persons/duplicate_persons.ex
  apps/ehealth/lib/ehealth/duplicate_persons/signals.ex
  apps/ehealth/lib/ehealth/web/controllers/deduplication_controller.ex
  apps/ehealth/lib/ehealth/web/router.ex
  apps/ehealth/test/integration/v1/deduplicating_persons_test.exs
Labels: status/in-progress

#3757 Add ability to sort legal_entity by nhs_reviewed
  apps/graphql/lib/graphql_web/schema/legal_entity_types.ex
  apps/graphql/test/web/resolvers/legal_entity_resolver_test.exs
Labels: status/in-progress

#3758 Changed status_reason column type in contracts and contract requests
  apps/core/priv/prm_repo/migrations/20181204141718_change_contracts_status_reason_column_type.exs
  apps/core/priv/repo/migrations/20181204140524_change_contract_requests_status_reason_column_type.exs
  apps/core/specs/json_schemas/contract/contract_terminate.json
  apps/core/specs/json_schemas/contract_request/contract_request_decline.json
  apps/ehealth/test/integration/v1/creating_declaration_request_test.exs
  apps/ehealth/test/integration/v2/creating_declaration_request_test.exs
  apps/ehealth/test/web/controllers/cabinet/declaration_request_controller_test.exs
  apps/ehealth/test/web/controllers/cabinet/persons_controller_test.exs
  apps/ehealth/test/web/controllers/contract_controller_test.exs
  apps/ehealth/test/web/controllers/contract_request/capitation_controller_test.exs
  apps/ehealth/test/web/controllers/legal_entity_controller_test.exs
  apps/ehealth/test/web/controllers/medication_dispense_controller_test.exs
  apps/ehealth/test/web/controllers/person_controller_test.exs
Labels: status/in-progress

#3763 add defaults to filtering middleware
  apps/graphql/lib/graphql_web/middleware/filtering.ex
  apps/graphql/test/unit/middleware/filtering_middleware_test.exs
Labels: status/in-progress

#3761 sign medication request request - new attributes to save to db #3726
  apps/core/lib/core/employees/renderer.ex
  apps/core/lib/core/medication_request_requests/renderer.ex
  apps/core/lib/core/medication_request_requests/sign_operation.ex
  apps/core/lib/core/medication_request_requests/validations.ex
  apps/core/lib/core/medications/innm_dosage/renderer.ex
  apps/core/lib/core/parties/renderer.ex
  apps/core/test/support/expectations/rpc.ex
  apps/ehealth/lib/ehealth/web/views/employee_view.ex
  apps/ehealth/lib/ehealth/web/views/medication/innm_dosage_view.ex
  apps/ehealth/lib/ehealth/web/views/medication_request_request_view.ex
  apps/ehealth/lib/ehealth/web/views/party_view.ex
  apps/ehealth/test/web/controllers/medication_request_request_controller_test.exs
Labels: [zube]: Inbox, status/in-progress

#3719 Dictionaries
  apps/core/priv/repo/fixtures/dictionaries.json
Labels: [zube]: Inbox, status/in-progress

#3766 medication request request create fixed #3574
  apps/core/lib/core/medication_request_requests/renderer.ex
  apps/core/specs/json_schemas/medication_request_request/medication_request_request_list_response.json
  apps/core/specs/json_schemas/medication_request_request/medication_request_request_plan_show_response.json
  apps/ehealth/test/web/controllers/medication_request_request_controller_test.exs
Labels: [zube]: In Progress, status/in-progress

#3767 Added "service_request" to "resources" dictionary
  apps/core/priv/repo/fixtures/dictionaries.json
Labels: status/in-progress

#3765 Format errors on graphql
  apps/graphql/lib/graphql/jobs/jobs.ex
  apps/graphql/lib/graphql_web/resolvers/contract_request_resolver.ex
  apps/graphql/lib/graphql_web/resolvers/helpers/errors.ex
  apps/graphql/lib/graphql_web/resolvers/legal_entity_merge_job_resolver.ex
  apps/graphql/test/unit/helpers/errors_test.exs
  apps/graphql/test/web/resolvers/contract_request_resolver_test.exs
Labels: status/in-progress

#3769 Validate status and nhs_review on legal_entity mutations
  apps/core/lib/core/legal_entities/legal_entities.ex
  apps/graphql/lib/graphql_web/resolvers/legal_entity_resolver.ex
  apps/graphql/lib/graphql_web/schema/legal_entity_types.ex
  apps/graphql/test/web/resolvers/legal_entity_resolver_test.exs
Labels: status/in-progress

#3771 Removed pattern check from json_schema for status_reason
  apps/core/specs/json_schemas/contract/contract_terminate.json
  apps/core/specs/json_schemas/contract_request/contract_request_decline.json
  apps/ehealth/test/web/controllers/contract_controller_test.exs
  apps/ehealth/test/web/controllers/contract_request/capitation_controller_test.exs
Labels: status/in-progress

#3786 Decreased_enum_of_values_in_ME_dictionaries
  apps/core/priv/repo/fixtures/dictionaries.json
Labels: status/in-progress

#3784 Add reimbursement contract request schema
  apps/core/lib/core/contract_requests/reimbursement/contract_request.ex
  apps/core/lib/elixir/calendar/date_interval.ex
  apps/graphql/features/capitation_contract_requests/get_all.feature
  apps/graphql/features/capitation_contract_requests/get_specific.feature
  apps/graphql/features/contexts/context.exs
  apps/graphql/features/reimbursement_contract_requests/get_all.feature
  apps/graphql/features/reimbursement_contract_requests/get_specific.feature
  apps/graphql/lib/graphql/helpers/filtering.ex
  apps/graphql/lib/graphql_web/loaders/il.ex
  apps/graphql/lib/graphql_web/resolvers/reimbursement_contract_request_resolver.ex
  apps/graphql/lib/graphql_web/schema.ex
  apps/graphql/lib/graphql_web/schema/capitation_contract_request_types.ex
  apps/graphql/lib/graphql_web/schema/contract_request_types.ex
  apps/graphql/lib/graphql_web/schema/contract_types.ex
  apps/graphql/lib/graphql_web/schema/employee_types.ex
  apps/graphql/lib/graphql_web/schema/medical_program_types.ex
  apps/graphql/lib/graphql_web/schema/reimbursement_contract_request_types.ex
  apps/graphql/test/unit/helpers/filtering_helper_test.exs
  apps/graphql/test/web/resolvers/contract_request_resolver_test.exs
Labels: status/in-progress

#3785 Added replication to fraud db for some new tables
  apps/core/priv/fraud_repo/migrations/20181206111458_create_contracts.exs
  apps/core/priv/fraud_repo/migrations/20181206141318_create_contract_divisions.exs
  apps/core/priv/fraud_repo/migrations/20181206141524_create_contract_employees.exs
  apps/core/priv/fraud_repo/migrations/20181206142318_create_contract_requests.exs
Labels: status/in-progress

#3790 Fixes to fraud db replication
  apps/core/priv/fraud_repo/migrations/20181206111458_create_contracts.exs
  apps/core/priv/fraud_repo/migrations/20181206142318_create_contract_requests.exs
  apps/core/priv/fraud_repo/migrations/20181207105129_add_id_to_dictionaries.exs
Labels: status/in-progress

#3746 Split contracts schema on graphql
  apps/graphql/lib/graphql_web/loaders/prm.ex
  apps/graphql/lib/graphql_web/resolvers/capitation_contract_resolver.ex
  apps/graphql/lib/graphql_web/resolvers/contract_resolver.ex
  apps/graphql/lib/graphql_web/resolvers/helpers/load.ex
  apps/graphql/lib/graphql_web/resolvers/reimbursement_contract_resolver.ex
  apps/graphql/lib/graphql_web/schema.ex
  apps/graphql/lib/graphql_web/schema/capitation_contract_request_types.ex
  apps/graphql/lib/graphql_web/schema/capitation_contract_types.ex
  apps/graphql/lib/graphql_web/schema/contract_types.ex
  apps/graphql/lib/graphql_web/schema/legal_entity_types.ex
  apps/graphql/lib/graphql_web/schema/reimbursement_contract_request_types.ex
  apps/graphql/lib/graphql_web/schema/reimbursement_contract_types.ex
  apps/graphql/test/web/resolvers/capitation_contract_resolver_test.exs
  apps/graphql/test/web/resolvers/contract_request_resolver_test.exs
  apps/graphql/test/web/resolvers/contract_resolver_test.exs
  apps/graphql/test/web/resolvers/legal_entity_resolver_test.exs
  apps/graphql/test/web/resolvers/reimbursement_contract_resolver_test.exs
Labels: [zube]: Inbox, status/in-progress

#3793 Qualify medication request changes #3698
  apps/core/lib/core/medication_requests/api.ex
  apps/ehealth/test/web/controllers/medication_request_controller_test.exs
Labels: status/in-progress

#3799 3431 contract requests auto termination
  .travis.yml
  apps/core/lib/core/contract_requests/contract_requests.ex
  apps/ehealth_scheduler/.formatter.exs
  apps/ehealth_scheduler/.gitignore
  apps/ehealth_scheduler/README.md
  apps/ehealth_scheduler/config/config.exs
  apps/ehealth_scheduler/config/dev.exs
  apps/ehealth_scheduler/config/prod.exs
  apps/ehealth_scheduler/config/test.exs
  apps/ehealth_scheduler/lib/ehealth_scheduler/application.ex
  apps/ehealth_scheduler/lib/ehealth_scheduler/jobs/contract_requests_terminator.ex
  apps/ehealth_scheduler/lib/ehealth_scheduler/worker.ex
  apps/ehealth_scheduler/mix.exs
  apps/ehealth_scheduler/test/jobs/contract_requests_terminator_test.exs
  apps/ehealth_scheduler/test/test_helper.exs
  rel/config.exs
Labels: status/in-progress

#3803 deactivate employees iteratively
  apps/core/lib/core/legal_entities/legal_entity_updater.ex
  apps/core/test/support/expectations/mithril.ex
  apps/ehealth/test/web/controllers/legal_entity_controller_test.exs
Labels: status/in-progress

#3797 Add intent to query params #3772
  apps/core/lib/core/medication_request_requests/api.ex
  apps/core/lib/core/medication_request_requests/search.ex
  apps/core/lib/core/medication_requests/search.ex
  apps/ehealth/test/web/controllers/medication_request_request_controller_test.exs
Labels: status/in-progress

#3806 Fix resolving printoutContent for contracts
  apps/core/lib/core/contract_requests/request_pack.ex
  apps/graphql/lib/graphql_web/resolvers/contract_request_resolver.ex
  apps/graphql/lib/graphql_web/resolvers/contract_resolver.ex
  apps/graphql/lib/graphql_web/schema/capitation_contract_types.ex
  apps/graphql/lib/graphql_web/schema/reimbursement_contract_types.ex
  apps/graphql/test/web/resolvers/capitation_contract_resolver_test.exs
  apps/graphql/test/web/resolvers/reimbursement_contract_resolver_test.exs
Labels: status/in-progress

#3805 Now contract request auto termination works in chunks
  apps/ehealth_scheduler/config/config.exs
  apps/ehealth_scheduler/lib/ehealth_scheduler/jobs/contract_requests_terminator.ex
  apps/ehealth_scheduler/test/jobs/contract_requests_terminator_test.exs
Labels: status/in-progress

#3807 intent validation added on medication dispense create #3478
  apps/core/lib/core/medication_dispenses/api.ex
  apps/ehealth/test/web/controllers/medication_dispense_controller_test.exs
Labels: status/in-progress

#3809 Resolve attached documents on ReimbursementContractRequest
  apps/graphql/lib/graphql_web/schema/reimbursement_contract_request_types.ex
  apps/graphql/test/web/resolvers/capitation_contract_request_resolver_test.exs
  apps/graphql/test/web/resolvers/reimbursement_contract_request_resolver_test.exs
Labels: status/in-progress

#3811 Contract validation on medication dispense improved #3359
  apps/core/lib/core/medication_dispenses/api.ex
  apps/ehealth/test/web/controllers/medication_dispense_controller_test.exs
Labels: status/in-progress

#3815 Fix termination for reimbursement contracts
  apps/core/lib/core/contract_requests/request_pack.ex
  apps/core/lib/core/contracts/contracts.ex
  apps/ehealth/lib/ehealth/web/controllers/contract_controller.ex
  apps/graphql/lib/graphql_web/resolvers/contract_resolver.ex
  apps/graphql/test/web/resolvers/contract_resolver_test.exs
Labels: status/in-progress

#3830 Validate contractor_owner by contract type
  apps/core/lib/core/contract_requests/validator.ex
  apps/ehealth/test/web/controllers/contract_request/reimbursement_controller_test.exs
Labels: status/in-progress

#3835 filter related_legal_entity with is_active=true condition
  apps/graphql/lib/graphql_web/resolvers/contract_resolver.ex
  apps/graphql/test/web/resolvers/capitation_contract_resolver_test.exs
Labels: status/in-progress

#3833 add root Query fields for MedicalProgram
  apps/graphql/features/contexts/context.exs
  apps/graphql/features/medical_programs/get_all.feature
  apps/graphql/features/medical_programs/get_specific.feature
  apps/graphql/lib/graphql_web/resolvers/medical_program_resolver.ex
  apps/graphql/lib/graphql_web/schema.ex
  apps/graphql/lib/graphql_web/schema/medical_program_types.ex
Labels: status/in-progress

#3837 fix access to Contract Request by client type
  apps/core/lib/core/contract_requests/validator.ex
  apps/core/test/support/expectations/mithril.ex
  apps/ehealth/test/web/controllers/contract_request/reimbursement_controller_test.exs
Labels: status/in-progress

#3836 use rpc for uaddresses validation
  apps/core/lib/core/cabinet/api.ex
  apps/core/lib/core/declaration_requests/v1/declaration_requests.ex
  apps/core/lib/core/declaration_requests/v2/declaration_requests.ex
  apps/core/lib/core/divisions/divisions.ex
  apps/core/lib/core/legal_entities/validator.ex
  apps/core/lib/core/persons/persons.ex
  apps/core/lib/core/validators/addresses.ex
  apps/core/test/support/conn_case.ex
  apps/core/test/support/expectations/rpc.ex
  apps/core/test/unit/legal_entity_test.exs
  apps/core/test/unit/validators/addresses_validator_test.exs
  apps/ehealth/config/config.exs
  apps/ehealth/lib/ehealth.ex
  apps/ehealth/test/integration/cabinet/registration_test.exs
  apps/ehealth/test/integration/v1/creating_declaration_request_test.exs
  apps/ehealth/test/integration/v2/creating_declaration_request_test.exs
  apps/ehealth/test/support/conn_case.ex
  apps/ehealth/test/web/controllers/cabinet/auth_controller_test.exs
  apps/ehealth/test/web/controllers/cabinet/persons_controller_test.exs
  apps/ehealth/test/web/controllers/divisions_controller_test.exs
  apps/ehealth/test/web/controllers/legal_entity_controller_test.exs
Labels: [zube]: In Progress, status/in-progress

#3838 bump libcluster
  apps/ehealth/lib/ehealth.ex
  apps/ehealth/lib/ehealth/contracts/terminator.ex
  mix.lock
Labels: status/in-progress

#3839 fix rpc behaviour
  apps/core/lib/core/api/behaviours/rpc_worker_behaviour.ex
  apps/core/lib/core/medication_request_requests/validations.ex
  apps/core/lib/core/validators/addresses.ex
  apps/core/test/support/expectations/rpc.ex
Labels: status/in-progress

#3843 Fix decline process for reimbursement contract requests
  apps/core/lib/core/contract_requests/contract_requests.ex
  apps/ehealth/lib/ehealth/web/controllers/contract_request_controller.ex
  apps/ehealth/test/web/controllers/contract_request/reimbursement_controller_test.exs
  apps/graphql/lib/graphql_web/resolvers/contract_request_resolver.ex
  apps/graphql/lib/graphql_web/schema/contract_request_types.ex
  apps/graphql/test/web/resolvers/reimbursement_contract_request_resolver_test.exs
Labels: status/in-progress

#3846 fix validation for duplicated RCR id
  apps/core/lib/core/contract_requests/contract_requests.ex
  apps/ehealth/test/web/controllers/contract_request/reimbursement_controller_test.exs
Labels: status/in-progress

#3850 removed type from request json schemas
  apps/core/lib/core/contract_requests/contract_requests.ex
  apps/core/lib/core/contract_requests/validator.ex
  apps/core/specs/json_schemas/contract_request/capitation_contract_request_create.json
  apps/core/specs/json_schemas/contract_request/contract_request_create.json
  apps/core/specs/json_schemas/contract_request/reimbursement_contract_request_create.json
  apps/ehealth/test/web/controllers/contract_request/capitation_controller_test.exs
  apps/ehealth/test/web/controllers/contract_request/reimbursement_controller_test.exs
Labels: status/in-progress

#3851 validate previous request with RequestPack
  apps/core/lib/core/contract_requests/contract_requests.ex
  apps/core/lib/core/contract_requests/validator.ex
  apps/ehealth/test/web/controllers/contract_request/reimbursement_controller_test.exs
Labels: status/in-progress

#3848 add filter on party's full name to employees field
  apps/graphql/features/contexts/context.exs
  apps/graphql/features/employees/get_all.feature
  apps/graphql/features/employees/get_specific.feature
  apps/graphql/features/reimbursement_contract_requests/get_all.feature
  apps/graphql/lib/graphql/helpers/filtering.ex
  apps/graphql/lib/graphql_web/resolvers/employee_resolver.ex
  apps/graphql/lib/graphql_web/schema.ex
  apps/graphql/lib/graphql_web/schema/employee_types.ex
  apps/graphql/lib/graphql_web/schema/party_types.ex
  apps/graphql/test/web/resolvers/employee_resolver_test.exs
Labels: status/in-progress

#3845 Return only certain type of contracts and contractRequests on graphql
  apps/graphql/features/capitation_contract_requests/get_all.feature
  apps/graphql/features/capitation_contracts/get_all.feature
  apps/graphql/features/contexts/context.exs
  apps/graphql/features/reimbursement_contract_requests/get_all.feature
  apps/graphql/features/reimbursement_contracts/get_all.feature
  apps/graphql/lib/graphql_web/resolvers/capitation_contract_request_resolver.ex
  apps/graphql/lib/graphql_web/resolvers/capitation_contract_resolver.ex
  apps/graphql/lib/graphql_web/resolvers/contract_resolver.ex
  apps/graphql/lib/graphql_web/resolvers/reimbursement_contract_request_resolver.ex
  apps/graphql/lib/graphql_web/resolvers/reimbursement_contract_resolver.ex
  apps/graphql/test/web/resolvers/capitation_contract_request_resolver_test.exs
  apps/graphql/test/web/resolvers/capitation_contract_resolver_test.exs
  apps/graphql/test/web/resolvers/reimbursement_contract_request_resolver_test.exs
  apps/graphql/test/web/resolvers/reimbursement_contract_resolver_test.exs
Labels: status/in-progress

#3735 EHealth-3448: added validation logic for reimbursement contract request update
  apps/core/lib/core/contract_requests/contract_requests.ex
  apps/core/lib/core/contract_requests/request_pack.ex
  apps/core/lib/core/contract_requests/validator.ex
  apps/core/lib/core/validators/json_schema.ex
  apps/core/specs/json_schemas/contract_request/capitation/contract_request_create.json
  apps/core/specs/json_schemas/contract_request/capitation/contract_request_show_response.json
  apps/core/specs/json_schemas/contract_request/capitation/contract_request_update.json
  apps/core/specs/json_schemas/contract_request/contract_request_update.json
  apps/core/specs/json_schemas/contract_request/reimbursement/contract_request_create.json
  apps/core/specs/json_schemas/contract_request/reimbursement/contract_request_show_response.json
  apps/core/specs/json_schemas/contract_request/reimbursement/contract_request_update.json
  apps/ehealth/lib/ehealth/web/controllers/contract_request_controller.ex
  apps/ehealth/test/web/controllers/contract_request/capitation_controller_test.exs
  apps/ehealth/test/web/controllers/contract_request/reimbursement_controller_test.exs
  apps/graphql/lib/graphql_web/resolvers/contract_request_resolver.ex
  apps/graphql/lib/graphql_web/schema/contract_request_types.ex
  apps/graphql/lib/graphql_web/schema/reimbursement_contract_request_types.ex
  apps/graphql/test/web/resolvers/reimbursement_contract_request_resolver_test.exs
Labels: [zube]: Inbox, status/in-progress

#3854 Schema improvements for new medication request
  apps/core/priv/repo/fixtures/dictionaries.json
  apps/core/specs/json_schemas/medication_request/medication_request_list_response.json
  apps/core/specs/json_schemas/medication_request/medication_request_reject_content_order.json
  apps/core/specs/json_schemas/medication_request/medication_request_reject_content_plan.json
  apps/core/specs/json_schemas/medication_request/medication_request_show_response.json
  apps/core/specs/json_schemas/medication_request_request/medication_request_request_create_order.json
  apps/core/specs/json_schemas/medication_request_request/medication_request_request_create_plan.json
  apps/core/specs/json_schemas/medication_request_request/medication_request_request_list_response.json
  apps/core/specs/json_schemas/medication_request_request/medication_request_request_plan_show_response.json
  apps/core/specs/json_schemas/medication_request_request/medication_request_request_prequalify_request.json
  apps/core/specs/json_schemas/medication_request_request/medication_request_request_show_response.json
  apps/core/test/data/medication_request_request/medication_request_request.json
  apps/core/test/support/ops_factories/medication_request_factory.ex
Labels: status/in-progress

#3855 add new medication_request fields to fraud replica
  apps/core/priv/fraud_repo/migrations/20181213122707_medication_request_updates.exs
Labels: status/in-progress

#3858 GraphQL Release contract creation hotfix
  apps/core/lib/core/contract_requests/contract_requests.ex
  apps/core/lib/core/contract_requests/validator.ex
  apps/ehealth/test/web/controllers/contract_request/reimbursement_controller_test.exs
Labels: status/in-progress

#3856 Add legal_entity edrpou check on merge_legal_entities job
  apps/core/lib/core/contract_requests/validator.ex
  apps/core/test/support/prm_factories/party_factory.ex
  apps/graphql/lib/graphql/jobs/jobs.ex
  apps/graphql/test/web/resolvers/legal_entity_merge_job_resolver_test.exs
Labels: status/in-progress

#3859 Reimbursement Contract Request - update assignee
  apps/core/lib/core/contract_requests/contract_requests.ex
  apps/core/lib/core/contract_requests/validator.ex
  apps/ehealth/lib/ehealth/web/controllers/contract_request_controller.ex
  apps/graphql/lib/graphql_web/resolvers/contract_request_resolver.ex
  apps/graphql/lib/graphql_web/schema/contract_request_types.ex
  apps/graphql/test/web/resolvers/reimbursement_contract_request_resolver_test.exs
Labels: status/in-progress

#3857 sign ContractRequest by NHS
  apps/core/lib/core/contract_requests/contract_requests.ex
  apps/core/lib/core/divisions/divisions.ex
  apps/core/lib/core/man/templates/contract_request_printout_form.ex
  apps/ehealth/lib/ehealth/web/controllers/contract_request_controller.ex
  apps/graphql/lib/graphql_web/resolvers/contract_request_resolver.ex
  apps/graphql/lib/graphql_web/schema/contract_request_types.ex
  apps/graphql/test/web/resolvers/reimbursement_contract_request_resolver_test.exs
Labels: status/in-progress

#3864 Improved schema for medication request reject
  apps/core/specs/json_schemas/medication_request/medication_request_reject_content_plan.json
  apps/core/specs/json_schemas/medication_request_request/medication_request_request_create_plan.json
Labels: status/in-progress

#3865 Contract request filter changes
  apps/core/lib/core/contract_requests/capitation/contract_request.ex
  apps/core/lib/core/contract_requests/reimbursement/contract_request.ex
  apps/graphql/features/capitation_contract_requests/get_all.feature
  apps/graphql/features/contexts/context.exs
  apps/graphql/features/employees/get_all.feature
  apps/graphql/features/reimbursement_contract_requests/get_all.feature
  apps/graphql/features/reimbursement_contract_requests/get_specific.feature
  apps/graphql/lib/graphql_web/loaders/il.ex
  apps/graphql/lib/graphql_web/loaders/prm.ex
  apps/graphql/lib/graphql_web/resolvers/capitation_contract_request_resolver.ex
  apps/graphql/lib/graphql_web/resolvers/capitation_contract_resolver.ex
  apps/graphql/lib/graphql_web/resolvers/contract_request_resolver.ex
  apps/graphql/lib/graphql_web/resolvers/contract_resolver.ex
  apps/graphql/lib/graphql_web/resolvers/helpers/load.ex
  apps/graphql/lib/graphql_web/resolvers/reimbursement_contract_request_resolver.ex
  apps/graphql/lib/graphql_web/resolvers/reimbursement_contract_resolver.ex
  apps/graphql/lib/graphql_web/schema/capitation_contract_request_types.ex
  apps/graphql/lib/graphql_web/schema/contract_types.ex
  apps/graphql/lib/graphql_web/schema/employee_types.ex
  apps/graphql/lib/graphql_web/schema/reimbursement_contract_request_types.ex
  apps/graphql/lib/graphql_web/schema/reimbursement_contract_types.ex
  apps/graphql/test/web/resolvers/capitation_contract_request_resolver_test.exs
  apps/graphql/test/web/resolvers/reimbursement_contract_resolver_test.exs
Labels: status/in-progress

#3869 add missing resolvers to reimbursement contract request raw data fields
  apps/graphql/lib/graphql_web/schema/reimbursement_contract_request_types.ex
Labels: status/in-progress

#3871 Handle graphql exceptions with error view
  apps/core/lib/core/log.ex
  apps/graphql/config/config.exs
  apps/graphql/lib/graphql/jobs/legal_entity_merge_job.ex
  apps/graphql/lib/graphql_web/resolvers/helpers/error_view.ex
  apps/graphql/lib/graphql_web/resolvers/helpers/errors.ex
Labels: status/in-progress

#3876 don't clean up documents on declaration_request terminate
  apps/ehealth/lib/ehealth/declaration_requests/terminator.ex
  apps/ehealth/test/unit/declaration_requests/terminator_test.exs
Labels: status/in-progress

#3867 Add name, activeness, labels validations to dictionaries
  apps/core/lib/core/dictionaries/dictionaries.ex
  apps/ehealth/test/web/controllers/dictionary_controller_test.exs
  apps/graphql/lib/graphql_web/schema/dictionary_types.ex
  apps/graphql/test/web/resolvers/dictionary_resolver_test.exs
Labels: status/in-progress

#3882 use separate repo for il read queries
  .env
  apps/casher/test/support/conn_case.ex
  apps/core/config/config.exs
  apps/core/config/dev.exs
  apps/core/config/prod.exs
  apps/core/config/test.exs
  apps/core/lib/application.ex
  apps/core/lib/core/cabinet/declaration_requests/declaration_requests.ex
  apps/core/lib/core/contract_requests/contract_requests.ex
  apps/core/lib/core/contract_requests/validator.ex
  apps/core/lib/core/declaration_requests/api/v1/approve.ex
  apps/core/lib/core/declaration_requests/api/v1/creator.ex
  apps/core/lib/core/declaration_requests/v1/declaration_requests.ex
  apps/core/lib/core/dictionaries/dictionaries.ex
  apps/core/lib/core/employee_requests/employee_requests.ex
  apps/core/lib/core/medication_request_requests/api.ex
  apps/core/lib/core/read_repo.ex
  apps/core/lib/core/users/api.ex
  apps/core/lib/core/validators/cache.ex
  apps/ehealth/test/support/conn_case.ex
  apps/ehealth/test/test_helper.exs
  apps/graphql/lib/graphql_web/loaders/il.ex
  apps/graphql/lib/graphql_web/resolvers/dictionary_resolver.ex
  apps/graphql/test/support/conn_case.ex
Labels: status/in-progress

#3884 use separate repo for prm read queries
  .env
  apps/casher/lib/casher/person_data.ex
  apps/casher/test/support/conn_case.ex
  apps/core/config/config.exs
  apps/core/config/dev.exs
  apps/core/config/prod.exs
  apps/core/config/test.exs
  apps/core/lib/application.ex
  apps/core/lib/core/black_list_users/black_list_users.ex
  apps/core/lib/core/contract_requests/validator.ex
  apps/core/lib/core/contracts/contracts.ex
  apps/core/lib/core/contracts/validator.ex
  apps/core/lib/core/divisions/divisions.ex
  apps/core/lib/core/employee_requests/employee_requests.ex
  apps/core/lib/core/employees/employee_creator.ex
  apps/core/lib/core/employees/employee_updater.ex
  apps/core/lib/core/employees/employees.ex
  apps/core/lib/core/global_parameters/global_parameters.ex
  apps/core/lib/core/legal_entities/legal_entities.ex
  apps/core/lib/core/legal_entities/registries.ex
  apps/core/lib/core/man/templates/contract_request_printout_form.ex
  apps/core/lib/core/medical_programs/medical_programs.ex
  apps/core/lib/core/medication_dispenses/api.ex
  apps/core/lib/core/medication_request_requests/api.ex
  apps/core/lib/core/medication_request_requests/operation_helpers.ex
  apps/core/lib/core/medication_requests/api.ex
  apps/core/lib/core/medications/medications.ex
  apps/core/lib/core/medications/validator.ex
  apps/core/lib/core/parties/parties.ex
  apps/core/lib/core/party_users/party_users.ex
  apps/core/lib/core/read_prm_repo.ex
  apps/core/lib/core/rpc/rpc.ex
  apps/core/test/support/conn_case.ex
  apps/ehealth/test/support/conn_case.ex
  apps/ehealth/test/test_helper.exs
  apps/graphql/lib/graphql/jobs/legal_entity_merge_job.ex
  apps/graphql/lib/graphql_web/loaders/prm.ex
  apps/graphql/lib/graphql_web/resolvers/contract_resolver.ex
  apps/graphql/lib/graphql_web/resolvers/employee_resolver.ex
  apps/graphql/lib/graphql_web/resolvers/legal_entity_resolver.ex
  apps/graphql/lib/graphql_web/resolvers/medical_program_resolver.ex
  apps/graphql/test/support/conn_case.ex
Labels: status/in-progress

#3883 ME prod dictionaries
  apps/core/priv/repo/fixtures/dictionaries.json
Labels: status/in-progress

#3849 Create mr date validations #3704
  apps/core/config/config.exs
  apps/core/lib/core/medication_request_requests/api.ex
  apps/core/lib/core/medication_request_requests/create_data_operation.ex
  apps/core/lib/core/medication_request_requests/operation_helpers.ex
  apps/core/lib/core/medication_request_requests/schema.ex
  apps/core/lib/core/medication_request_requests/validations.ex
  apps/core/lib/core/medication_requests/medication_request.ex
  apps/core/lib/core/rpc/rpc_error.ex
  apps/core/priv/prm_repo/migrations/20181211160511_global_parameter_medication_dispense_period.exs
  apps/core/specs/json_schemas/medication_request_request/medication_request_request_create_order.json
  apps/core/specs/json_schemas/medication_request_request/medication_request_request_create_plan.json
  apps/core/specs/json_schemas/medication_request_request/medication_request_request_list_response.json
  apps/core/specs/json_schemas/medication_request_request/medication_request_request_plan_show_response.json
  apps/core/specs/json_schemas/medication_request_request/medication_request_request_prequalify_request.json
  apps/core/test/data/medication_request_request/medication_request_request.json
  apps/core/test/support/expectations/rpc.ex
  apps/ehealth/config/config.exs
  apps/ehealth/test/web/controllers/medication_request_request_controller_test.exs
Labels: status/in-progress

#3891 fix config
  apps/ehealth/config/config.exs
Labels: status/in-progress

#3909 address building not required
  apps/graphql/lib/graphql_web/schema/address_types.ex
  apps/graphql/test/web/resolvers/reimbursement_contract_request_resolver_test.exs
Labels: status/in-progress

#3912 allow to delete party second_name on employee request create
  apps/core/specs/json_schemas/employee_request/employee_request_create_request.json
  apps/ehealth/test/web/controllers/employee_request_controller_test.exs
Labels: status/in-progress

#3911 Replace FilterArgument middleware with Filtering
  apps/graphql/lib/graphql_web/loaders/prm.ex
  apps/graphql/lib/graphql_web/middleware/filtering.ex
  apps/graphql/lib/graphql_web/resolvers/dictionary_resolver.ex
  apps/graphql/lib/graphql_web/resolvers/legal_entity_resolver.ex
  apps/graphql/lib/graphql_web/schema/capitation_contract_request_types.ex
  apps/graphql/lib/graphql_web/schema/capitation_contract_types.ex
  apps/graphql/lib/graphql_web/schema/dictionary_types.ex
  apps/graphql/lib/graphql_web/schema/division_types.ex
  apps/graphql/lib/graphql_web/schema/employee_types.ex
  apps/graphql/lib/graphql_web/schema/legal_entity_merge_job_types.ex
  apps/graphql/lib/graphql_web/schema/legal_entity_types.ex
  apps/graphql/lib/graphql_web/schema/reimbursement_contract_request_types.ex
  apps/graphql/lib/graphql_web/schema/reimbursement_contract_types.ex
  apps/graphql/lib/graphql_web/schema/scalar_types.ex
Labels: status/in-progress

#3918 fix second_name in employee request create json schema
  apps/core/specs/json_schemas/employee_request/employee_request_create_request.json
Labels: status/in-progress

#3920 create mrr response enriched with urgent data #3713
  apps/core/lib/core/medication_request_requests/api.ex
  apps/ehealth/lib/ehealth/web/controllers/medication_request_request_controller.ex
  apps/ehealth/test/web/controllers/medication_request_request_controller_test.exs
Labels: status/in-progress

#3921 Search#3319
  apps/core/lib/core/cabinet/api.ex
  apps/core/lib/core/declaration_requests/api/v1/creator.ex
  apps/core/lib/core/declaration_requests/api/v1/mpi_search.ex
  apps/core/lib/core/declaration_requests/api/v2/creator.ex
  apps/core/lib/core/declaration_requests/api/v2/mpi_search.ex
  apps/core/lib/core/declaration_requests/api/v2/persons.ex
  apps/core/lib/core/medication_request_requests/validations.ex
  apps/core/lib/core/validators/addresses.ex
  apps/core/test/support/expectations/rpc.ex
  apps/core/test/unit/declaration_requests/api/v1/creator_test.exs
  apps/core/test/unit/declaration_requests/api/v2/creator_test.exs
  apps/core/test/unit/declaration_requests/api/v2/persons_test.exs
  apps/ehealth/config/config.exs
  apps/ehealth/test/integration/cabinet/registration_test.exs
  apps/ehealth/test/integration/declaration_requests/api/v1/creator_test.exs
  apps/ehealth/test/integration/declaration_requests/api/v2/creator_test.exs
  apps/ehealth/test/integration/v1/creating_declaration_request_test.exs
  apps/ehealth/test/integration/v2/creating_declaration_request_test.exs
  apps/ehealth/test/web/controllers/cabinet/auth_controller_test.exs
Labels: status/in-progress

#3926 allow to set nullable owner second name
  apps/core/config/config.exs
  apps/core/specs/json_schemas/legal_entity/legal_entity_create_request.json
Labels: status/in-progress

#3927 Changed rpc basename in mpi search from mpi_api to mpi
  apps/core/lib/core/declaration_requests/api/v1/mpi_search.ex
  apps/core/lib/core/declaration_requests/api/v2/mpi_search.ex
Labels: status/in-progress

#3928 validations improved on sign mrr
  apps/core/lib/core/medication_request_requests/operation_helpers.ex
  apps/core/lib/core/medication_request_requests/sign_operation.ex
  apps/core/lib/core/medication_request_requests/validations.ex
  apps/ehealth/test/web/controllers/medication_request_request_controller_test.exs
Labels: status/in-progress

#3930 set declaration reason on declaration_request sign
  apps/core/lib/core/declaration_requests/api/v1/sign.ex
  apps/core/test/support/il_factories/declaration_request_factory.ex
  apps/ehealth/test/integration/declaration_requests/api/v1/sign_test.exs
Labels: status/in-progress

#3931 3319 search changes and fixes
  apps/core/lib/core/declaration_requests/api/v1/creator.ex
  apps/core/lib/core/persons/v2/validator.ex
  apps/core/test/unit/persons/v2/validate_person_test.exs
  apps/ehealth/test/integration/declaration_requests/api/v1/creator_test.exs
  apps/ehealth/test/integration/declaration_requests/api/v2/creator_test.exs
  apps/ehealth/test/integration/v1/creating_declaration_request_test.exs
  apps/ehealth/test/integration/v2/creating_declaration_request_test.exs
  apps/ehealth/test/web/controllers/cabinet/declaration_request_controller_test.exs
  apps/ehealth/test/web/controllers/declaration_request_controller_test.exs
Labels: status/in-progress

#3932 Changed no_tax_id validation since "tax_id" key is absent in content
  apps/core/lib/core/persons/v2/validator.ex
  apps/core/test/unit/persons/v2/validate_person_test.exs
  apps/ehealth/test/integration/v2/creating_declaration_request_test.exs
Labels: status/in-progress

#3923 Allow medication requests/dispenses without medical program
  apps/core/lib/core/medication_dispenses/api.ex
  apps/core/lib/core/medication_dispenses/renderer.ex
  apps/core/lib/core/medication_request_requests/schema.ex
  apps/core/lib/core/medication_requests/api.ex
  apps/core/specs/json_schemas/medication_dispense/medication_dispense_create_request.json
  apps/core/specs/json_schemas/medication_dispense/medication_dispense_list_response.json
  apps/core/specs/json_schemas/medication_dispense/medication_dispense_show_response.json
  apps/core/specs/json_schemas/medication_request/medication_request_reject_content_order.json
  apps/core/specs/json_schemas/medication_request_request/medication_request_request_create_order.json
  apps/core/specs/json_schemas/medication_request_request/medication_request_request_show_response.json
  apps/ehealth/test/web/controllers/medication_dispense_controller_test.exs
  apps/ehealth/test/web/controllers/medication_request_controller_test.exs
  apps/ehealth/test/web/controllers/medication_request_request_controller_test.exs
Labels: status/in-progress

#3933 add rpc casher server
  .gitignore
  apps/casher/lib/casher/rpc/rpc.ex
  apps/ehealth/mix.exs
  doc/.build
  doc/404.html
  doc/Casher.Rpc.html
  doc/api-reference.html
  doc/dist/html-c1666276880c0f8e3769.css
  doc/dist/html-c1666276880c0f8e3769.js
  doc/dist/html/fonts/icomoon.eot
  doc/dist/html/fonts/icomoon.svg
  doc/dist/html/fonts/icomoon.ttf
  doc/dist/html/fonts/icomoon.woff
  doc/dist/sidebar_items-044d2a7d85.js
  doc/index.html
  doc/search.html
  mix.exs
  mix.lock
Labels: status/in-progress

#3934 Fix contract details quering by type
  apps/core/lib/core/contracts/contracts.ex
  apps/core/lib/core/contracts/validator.ex
Labels: status/in-progress

#3935 fix contract request validation
  apps/core/lib/core/contract_requests/contract_requests.ex
  apps/core/lib/core/contract_requests/validator.ex
  apps/core/lib/core/employees/employees.ex
  apps/ehealth/test/web/controllers/contract_request/capitation_controller_test.exs
Labels: status/in-progress

#3936 Fix printout_content endpoint work with reimbursement contract_requests
  apps/core/lib/core/contract_requests/contract_requests.ex
  apps/ehealth/lib/ehealth/web/controllers/contract_request_controller.ex
  apps/ehealth/test/web/controllers/contract_request/reimbursement_controller_test.exs
Labels: status/in-progress

#3937 Fix match error on contract terminate
  apps/graphql/lib/graphql_web/resolvers/contract_resolver.ex
Labels: status/in-progress

#3938 Medication request validation improved
  apps/core/lib/core/medication_request_requests/operation_helpers.ex
  apps/core/lib/core/medication_request_requests/validations.ex
  apps/core/specs/json_schemas/medication_request_request/medication_request_request_create_order.json
  apps/core/specs/json_schemas/medication_request_request/medication_request_request_create_plan.json
  apps/ehealth/test/web/controllers/medication_request_request_controller_test.exs
Labels: status/in-progress

#3939 contract sign_msp validations fix
  apps/core/lib/core/contract_requests/contract_requests.ex
  apps/core/lib/core/contract_requests/validator.ex
Labels: status/in-progress

#3943 Save contractor_divisions of reimbursement contracts
  apps/core/lib/core/contracts/contracts/reimbursement_contract.ex
  apps/ehealth/test/web/controllers/contract_request/reimbursement_controller_test.exs
Labels: status/in-progress
